### ISSUE TITLE
Wand of plenty description isn't correct in this variant

### ISSUE THREAD

**Issue by nstoddard** [flend/RapidBrogue#2]
In BrogueCE 1.11.1, the description of the wand of plenty was reverted since it no longer halves the max health of the target. The wand still has its old description in Rapid Brogue, though, likely because the wand descriptions are [duplicated here](https://github.com/flend/RapidBrogue/blob/main/src/brogue/Globals.c#L3168).

**Comment by flend** [comment]
Yes, thanks, you're right. Fixed for the next version in e696f5184f4d9161cc880665d8473dfaf66992d8.
